education:
  project:
    per_page: 16
    truncate: 100
  technique:
    per_page: 6
    truncate: 100
  index:
    max_learning_program_desc: 150
    max_learning_program_name: 20
    max_learning_program: 3
  trainings:
    per_page: 5
  page_404_url: "public/404"
  related_project:
    limit: 20
  projects:
    textarea_rows: 8
  mess_success: "success"
  mess_notice: "notice"
  feedback_form_rows: 6
  feedback_form_cols: 30
  feedback:
    max_name_length: 50
    max_email_length: 255
    max_phone_number_length: 255
    max_subject_length: 255
    min_subject_length: 3
    min_content_length: 10
    max_content_length: 255
  post:
    title_max_length: 255
    title_min_length: 10
    content_min_length: 10
    content_max_length: 255
  category:
    name_max_length: 255
home:
  limit: 8
home_trainings_limit: 8
company:
  country: ["United States", "Japan", "Germany", "Korea"]
  max_length_name: 50
default_user_password: {"password": "123456"}
courses:
  home_limit: 4
  index_limit: 6
